### ISSUE TITLE
any_in_list is not a check to see if there is anything in the list

### ISSUE THREAD

**Issue by Ernie0013** [WolfDKs-CK3-Modding/Easier-Culture-Religion-Spread#1]
https://github.com/WolfDKs-CK3-Modding/Easier-Culture-Religion-Spread/blob/0c698290adc06f02d71801d1b26b3a32805905cc/events/auto_council_events.txt#L56-L60
I'd change the above to this:
```
limit = { 
    list_size = {
        name = heathens
        value > 0
    }
}
```

**Comment by andr9528** [comment]
Noted. It seems to work with the use of any_in_list, but checking the count is a way to be 100% sure, so I will implement that change.

**Comment by andr9528** [comment]
as noted by the commit, this has been implemented.
