### ISSUE TITLE
Add check to see if chaplain exists

### ISSUE THREAD

**Issue by Ernie0013** [WolfDKs-CK3-Modding/Easier-Culture-Religion-Spread#2]
https://github.com/WolfDKs-CK3-Modding/Easier-Culture-Religion-Spread/blob/0c698290adc06f02d71801d1b26b3a32805905cc/events/auto_council_events.txt#L68-L69

The chaplain doesn't necessarily exist. He could be dead and thus the position is vacant.
You could add it in with the limit above it.

**Comment by andr9528** [comment]
That suggested change has been implemented. but still thanks for the input.
