### ISSUE TITLE
Automated increase control task

### ISSUE THREAD

**Issue by maximusErectus** [WolfDKs-CK3-Modding/Easier-Culture-Religion-Spread#7]
Automating the martial's increase county control task.

**Comment by andr9528** [comment]
should have implemented this, but I haven't tested in game yet, so I will not close the issue just yet.

**Comment by andr9528** [comment]
missing additional section in description of task, telling what he will do when done.
- [x]  Add adaptive description section to Increase Control Task, that changes depending on automation flag

**Comment by andr9528** [comment]
Has been implemented, and as such I am closing the issue.
